### ISSUE TITLE
tool request: ansi-basic cross-compiler

### ISSUE THREAD

**Issue by ghost** [sikthehedgehog/mdtools#1]
are there plans to include an ansi-basic cross-compiler, that would work like Boriel’s ZX-Basic Compiler? (i know that there are BasiEgaXorz and SecondBasic, but these both are closed-source, very difficult to run on Wine, and very difficult to run from bash scripts)

**Comment by sikthehedgehog** [comment]
Wait what's ANSI BASIC? Unless you want something from the mainframe era (e.g. ECMA-55) there's no standard BASIC really, and those implementations were even weaker than what 8-bit home computers had. I doubt you're looking for that...

But anyway, nope, that'd be a project complex enough to warrant its own repository. This is a collection of simple tools to aid with development, mostly dealing with assets. Incidentally though I _do_ have a tokenizer for an unrelated thing, but other than splitting tokens it does nothing yet, and I'm not sure about it going anywhere.
